name: Publish Package to npmjs
on:
  release:
    types:
      - published
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chack out Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install npm with trusted publishing support
        run: npm install --global npm@11.5.1

      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Package
        run: pnpm run package

      - name: Deploy Package to NPM
        run: npm publish --access public
