name: Release Storybook to GitHubPages

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: pnpm/action-setup@v2
        with:
          node-version: 18.x

      - name: Install Node Dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Build storybook
        run: pnpm run build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/storybook